// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:167677930858:web:13341263455bc420b64913',
    messagingSenderId: '167677930858',
    projectId: 'login-4f735',
    authDomain: 'login-4f735.firebaseapp.com',
    storageBucket: 'login-4f735.appspot.com',
    measurementId: 'G-X19JH0LNTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:167677930858:android:3a83f6a45177c9afb64913',
    messagingSenderId: '167677930858',
    projectId: 'login-4f735',
    storageBucket: 'login-4f735.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:167677930858:ios:5e75f4f63d1495fab64913',
    messagingSenderId: '167677930858',
    projectId: 'login-4f735',
    storageBucket: 'login-4f735.appspot.com',
    iosClientId: '167677930858-28nri9ohao6hc12nvnq1cv1u0bd9hg98.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: '1:167677930858:ios:65f1cf7ec6fb01d1b64913',
    messagingSenderId: '167677930858',
    projectId: 'login-4f735',
    storageBucket: 'login-4f735.appspot.com',
    iosClientId: '167677930858-e0s8a8kfk0d47emdu2t021ngp7nd2bs6.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeApp.RunnerTests',
  );
}
